module.exports = function(config) {
    config.set({
        basePath:'.',
        frameworks:['jasmine'],
        files:[
            {pattern:'bower_components/moment/moment.js'},
            {pattern:'bower_components/angular/angular.js'},
            {pattern:'bower_components/angular-route/angular-route.js'},
            {pattern:'bower_components/angular-mocks/angular-mocks.js'},
            {pattern:'bower_components/binartajs/src/binarta.js'},
            {pattern:'bower_components/binartajs/src/application.js'},
            {pattern:'bower_components/binartajs/src/i18n.js'},
            {pattern:'bower_components/binartajs/src/gateways.inmem.js'},
            {pattern:'bower_components/binartajs-angular1/src/binarta-angular.js'},
            {pattern:'bower_components/binartajs-angular1/src/binarta-all-tpls-bootstrap3-angular1.js'},
            {pattern:'bower_components/binartajs-angular1/src/binarta-application-angular.js'},
            {pattern:'bower_components/binartajs-angular1/src/binarta-application-inmem-angular.js'},
            {pattern:'bower_components/binartajs-angular1/src/binarta-i18n-angular.js'},
            {pattern:'bower_components/thk-rest-client-mock/src/rest.client.mock.js'},
            {pattern:'bower_components/thk-notifications-mock/src/notifications.mock.js'},
            {pattern:'bower_components/binarta.web.storage.angular/src/web.storage.js'},
            {pattern:'bower_components/binarta.web.storage/src/web.storage.js'},
            {pattern:'bower_components/angular-moment/angular-moment.js'},
            {pattern:'bower_components/moment-picker/src/angular-moment-picker.js'},
            {pattern:'bower_components/binarta.momentx.angular/src/momentx.js'},
            {pattern:'bower_components/angular-bootstrap/ui-bootstrap.js'},
            {pattern:'src/main/**/*.js'},
            {pattern:'src/test/**/*.js'}
        ],
        browsers:['PhantomJS']
    });
};